=== afane20/testPlan/src/main/webapp/cs213/newXmlSchema.xsd
<?xml version="1.0"?>

<xs:schema version="1.0"
           xmlns:xs="http://www.w3.org/2001/XMLSchema"
           elementFormDefault="qualified">
           
    <xs:element name="street" type="xs:string" />
    <xs:element name="city" type ="xs:string"/>
    <xs:element name="state" type ="xs:string"/>  
    <xs:element name="firstName" type ="xs:string"/>
    <xs:element name="lastName" type ="xs:string"/>   
    <xs:element name="phoneNumber" type ="xs:string"/>
    <xs:attribute name="unitName" type="xs:string"/>
    <xs:attribute name="number" type="xs:string"/>
    <xs:attribute name="dateEarn" type="xs:string"/>
    <xs:attribute name="name" type="xs:string"/>


    <xs:element name="bsa">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="council" maxOccurs="unbounded"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    
    <xs:element name="council">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="troop" maxOccurs="unbounded"/>
            </xs:sequence>
            <xs:attribute ref="name" use="required"/>
        </xs:complexType>
    </xs:element>
    
    <xs:element name="troop">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref = "scout" maxOccurs="unbounded"/>
            </xs:sequence>
            <xs:attribute ref = "number" use = "required"/>
            <xs:attribute ref = "unitName" use = "required"/>
        </xs:complexType>
    </xs:element>
    
    <xs:element name="scout">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="firstName"/>
                <xs:element ref="lastName" />
                <xs:element ref="phoneNumber"/>
                <xs:element ref="address"/>
                <xs:element ref="rank" maxOccurs="unbounded"/>
                <xs:element ref="meritBadge" maxOccurs="unbounded"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    
    <xs:element name="address">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref= "street"/>
                <xs:element ref= "city"/>
                <xs:element ref= "state"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    
    <xs:element name="meritBadge">
        <xs:complexType>
            <xs:attribute ref = "dateEarn" use="required"/>
        </xs:complexType>
    </xs:element>
    
     <xs:element name="rank">
        <xs:complexType>
            <xs:attribute ref = "dateEarn" use="required"/>
        </xs:complexType>
    </xs:element>
   
        
       
</xs:schema>

=== afane20/testPlan/src/main/webapp/CS200/public_html/assign7/assign07_xsd.xml
<?xml version="1.0" encoding="UTF-8"?>

<bsa xmlns="http://www.w3schools.com"
xmlns:xs="http://www.w3.org/2001/XMLSchema-instance"
xs:schemaLocation="http://www.w3schools.com newXmlSchema.xsd">

    <council name="LightPower">
        <troop number="1" unitName="unit1">
            <scout>
                <firstName>Manuel</firstName>
                <lastName>Black</lastName>
                <phoneNumber>333-222-1111</phoneNumber>
                <address>
                    <street>3195 Knox McRae</street>
                    <city>Orlando</city>
                    <state>Florida</state>
                </address>
                <rank dateEarn = "2014-5-30">Eagle</rank>
                <meritBadge dateEarn = "2014-5-30">Cooking</meritBadge>
            </scout>
            <scout>
                <firstName>Peter</firstName>
                <lastName>Black</lastName>
                <phoneNumber>333-222-1111</phoneNumber>
                <address>
                    <street>3198 Knox McRae</street>
                    <city>Orlando</city>
                    <state>Florida</state>
                </address>
                <rank dateEarn = "2013-3-28">Eagle</rank>
                <meritBadge dateEarn = "2013-3-28">Cooking</meritBadge>
                <meritBadge dateEarn = "2013-3-28">Swimming</meritBadge>
                <meritBadge dateEarn = "2013-3-28">Corageous</meritBadge>
                <meritBadge dateEarn = "2013-3-28">Leader</meritBadge>
                <meritBadge dateEarn = "2013-3-28">Communicator</meritBadge>
                <meritBadge dateEarn = "2013-3-28">Enthusiastic</meritBadge>
                <meritBadge dateEarn = "2013-3-28">Eater</meritBadge>
                <meritBadge dateEarn = "2013-3-28">Fishing</meritBadge>
                <meritBadge dateEarn = "2013-3-28">Recueter</meritBadge>
                <meritBadge dateEarn = "2013-3-28">crafting</meritBadge>
            </scout>
            <scout>
                <firstName>Magus</firstName>
                <lastName>Black</lastName>
                <phoneNumber>333-222-1111</phoneNumber>
                <address>
                    <street>3195 Knox McRae</street>
                    <city>Orlando</city>
                    <state>Texas</state>
                </address>
                <rank dateEarn = "2013-3-28">Dictator</rank>
                <meritBadge dateEarn = "2013-3-28">Cooking</meritBadge>
                <meritBadge dateEarn = "2013-3-28">Swimming</meritBadge>
                <meritBadge dateEarn = "2013-3-28">Corageous</meritBadge>
                <meritBadge dateEarn = "2013-3-28">Leader</meritBadge>
                <meritBadge dateEarn = "2013-3-28">Communicator</meritBadge>
                <meritBadge dateEarn = "2013-3-28">Enthusiastic</meritBadge>
                <meritBadge dateEarn = "2013-3-28">Eater</meritBadge>
                <meritBadge dateEarn = "2013-3-28">Fishing</meritBadge>
                <meritBadge dateEarn = "2013-3-28">Recueter</meritBadge>
                <meritBadge dateEarn = "2013-3-28">Destroyer</meritBadge>
            </scout>
            <scout>
                <firstName>Manuel</firstName>
                <lastName>Black</lastName>
                <phoneNumber>333-222-1111</phoneNumber>
                <address>
                    <street>3195 Knox McRae</street>
                    <city>Orlando</city>
                    <state>Florida</state>
                </address>
                <rank dateEarn = "2013-3-28">Eagle</rank>
                <meritBadge dateEarn = "2013-3-28">Cooking</meritBadge>
            </scout>
            <scout>
                <firstName>Manuel</firstName>
                <lastName>Black</lastName>
                <phoneNumber>333-222-1111</phoneNumber>
                <address>
                    <street>3195 Knox McRae</street>
                    <city>Orlando</city>
                    <state>Florida</state>
                </address>
                <rank dateEarn = "2013-3-28">Eagle</rank>
                <meritBadge dateEarn = "2013-3-28">Cooking</meritBadge>
            </scout>
        </troop>
        <troop number="" unitName="">
            <scout>
                <firstName>Joseph</firstName>
                <lastName>Black</lastName>
                <phoneNumber>333-222-1111</phoneNumber>
                <address>
                    <street>3195 Knox McRae</street>
                    <city>Orlando</city>
                    <state>Florida</state>
                </address>
                <rank dateEarn = "2013-3-28">Eagle</rank>
                <meritBadge dateEarn = "2013-3-28">Cooking</meritBadge>
            </scout>
            <scout>
                <firstName>Manuel</firstName>
                <lastName>Black</lastName>
                <phoneNumber>333-222-1111</phoneNumber>
                <address>
                    <street>3195 Knox McRae</street>
                    <city>Orlando</city>
                    <state>Florida</state>
                </address>
                <rank dateEarn = "2013-3-28">Eagle</rank>
                <meritBadge dateEarn = "2013-3-28">Cooking</meritBadge>
            </scout>
            <scout>
                <firstName>Manuel</firstName>
                <lastName>Black</lastName>
                <phoneNumber>333-222-1111</phoneNumber>
                <address>
                    <street>3195 Knox McRae</street>
                    <city>Orlando</city>
                    <state>Florida</state>
                </address>
                <rank dateEarn = "2013-3-28">Eagle</rank>
                <meritBadge dateEarn = "2013-3-28">first Aid</meritBadge>
            </scout>
            <scout>
                <firstName>Manuel</firstName>
                <lastName>Black</lastName>
                <phoneNumber>333-222-1111</phoneNumber>
                <address>
                    <street>3195 Knox McRae</street>
                    <city>Orlando</city>
                    <state>Florida</state>
                </address>
                <rank dateEarn = "2013-3-28">Eagle</rank>
                <meritBadge dateEarn = "2013-3-28">Cooking</meritBadge>
            </scout>
            <scout>
                <firstName>Manuel</firstName>
                <lastName>Black</lastName>
                <phoneNumber>333-222-1111</phoneNumber>
                <address>
                    <street>3195 Knox McRae</street>
                    <city>Orlando</city>
                    <state>Florida</state>
                </address>
                <rank dateEarn = "2013-3-28">Eagle</rank>
                <meritBadge dateEarn = "2013-3-28">Life Saving</meritBadge>
            </scout>
            
        </troop>
    </council>
    <council name= "">
        <troop number="" unitName="">
            <scout>
                <firstName>Manuel</firstName>
                <lastName>Black</lastName>
                <phoneNumber>333-222-1111</phoneNumber>
                <address>
                    <street>3195 Knox McRae</street>
                    <city>Orlando</city>
                    <state>Florida</state>
                </address>
                <rank dateEarn = "2013-3-28">Eagle</rank>
                <meritBadge dateEarn = "2013-3-28">Enviromental Science</meritBadge>
            </scout>
            <scout>
                <firstName>Manuel</firstName>
                <lastName>Black</lastName>
                <phoneNumber>333-222-1111</phoneNumber>
                <address>
                    <street>3195 Knox McRae</street>
                    <city>Orlando</city>
                    <state>Florida</state>
                </address>
                <rank dateEarn = "2013-3-28">Eagle</rank>
                <meritBadge dateEarn = "2013-3-28">Cooking</meritBadge>
            </scout>
            <scout>
                <firstName>Manuel</firstName>
                <lastName>Black</lastName>
                <phoneNumber>333-222-1111</phoneNumber>
                <address>
                    <street>3195 Knox McRae</street>
                    <city>Orlando</city>
                    <state>Florida</state>
                </address>
                <rank dateEarn = "2013-3-28">Eagle</rank>
                <meritBadge dateEarn = "2013-3-28">Cooking</meritBadge>
            </scout>
            <scout>
                <firstName>Manuel</firstName>
                <lastName>Black</lastName>
                <phoneNumber>333-222-1111</phoneNumber>
                <address>
                    <street>3195 Knox McRae</street>
                    <city>Orlando</city>
                    <state>Florida</state>
                </address>
                <rank dateEarn = "2013-3-28">Eagle</rank>
                <meritBadge dateEarn = "2013-3-28">Cooking</meritBadge>
            </scout>
            <scout>
                <firstName>Manuel</firstName>
                <lastName>Black</lastName>
                <phoneNumber>333-222-1111</phoneNumber>
                <address>
                    <street>3195 Knox McRae</street>
                    <city>Orlando</city>
                    <state>Florida</state>
                </address>
                <rank dateEarn = "2013-3-28">Eagle</rank>
                <meritBadge dateEarn = "2013-3-28">Cooking</meritBadge>
            </scout>
        </troop>
        <troop number="" unitName="">
            <scout>
                <firstName>Manuel</firstName>
                <lastName>Black</lastName>
                <phoneNumber>333-222-1111</phoneNumber>
                <address>
                    <street>3195 Knox McRae</street>
                    <city>Orlando</city>
                    <state>Florida</state>
                </address>
                <rank dateEarn = "2013-3-28">Eagle</rank>
                <meritBadge dateEarn = "2013-3-28">Cooking</meritBadge>
            </scout>
            <scout>
                <firstName>Manuel</firstName>
