=== afane20/testPlan/src/main/webapp/cs213/public_html/cs213/f11/kyle/assign07.xsd
<?xml version="1.0" encoding="utf-8"?>

<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
    targetNamespace="http://www.byui.edu/assign07"
    xmlns="http://www.byui.edu/assign07"
    elementFormDefault="qualified">
  <xs:element name="firstName" type="xs:string" />
  <xs:element name="lastName" type="xs:string" />
  <xs:element name="street" type="xs:string" />
  <xs:element name="city" type="xs:string" />
  <xs:element name="state" type="xs:string" />

  <xs:element name="phone">
    <xs:simpleType>
      <xs:restriction base="xs:string">
        <xs:pattern value="[0-9]{3}-[0-9]{3}-[0-9]{4}" />
      </xs:restriction>
    </xs:simpleType>
  </xs:element>
  <xs:element name="rank">
    <xs:complexType>
      <xs:simpleContent>
        <xs:extension base="xs:string">
          <xs:attribute name="date-earned" type="xs:date" use="required" />
        </xs:extension>
      </xs:simpleContent>
    </xs:complexType>
  </xs:element>
  <xs:element name="meritbadge">
    <xs:complexType>
      <xs:simpleContent>
        <xs:extension base="xs:string">
          <xs:attribute name="date-earned" type="xs:date" use="required" />
        </xs:extension>
      </xs:simpleContent>
    </xs:complexType>
  </xs:element>

  <xs:element name="address">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="street" />
        <xs:element ref="city" />
        <xs:element ref="state" />
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="scout">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="firstName" />
        <xs:element ref="lastName" />
        <xs:element ref="phone" />
        <xs:element ref="address" />
        <xs:element ref="rank" minOccurs="0" maxOccurs="unbounded" />
        <xs:element ref="meritbadge" minOccurs="0" maxOccurs="unbounded" />
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="troop">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="scout" minOccurs="1" maxOccurs="unbounded" />
      </xs:sequence>
      <xs:attribute name="number" type="xs:integer" use="required" />
      <xs:attribute name="name" type="xs:string" use="required" />
    </xs:complexType>
  </xs:element>
  <xs:element name="council">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="troop" minOccurs="1" maxOccurs="unbounded" />
      </xs:sequence>
      <xs:attribute name="name" type="xs:string" use="required" />
    </xs:complexType>
  </xs:element>
  <xs:element name="bsa">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="council" minOccurs="1" maxOccurs="unbounded" />
      </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== afane20/testPlan/src/main/webapp/cs213/public_html/cs213/f11/kyle/assign08.xml
<?xml version="1.0" encoding="utf-8"?>
<?xml-stylesheet type="text/xsl" href="assign08.xsl"?>
<bsa xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://www.byui.edu/assign07 assign07.xsd">
  <council name="Ore-Ida">
    <troop number="213" name="Nampa North">
      <scout>
        <firstName>Tommy</firstName>
        <lastName>Tootles</lastName>
        <phone>208-123-4567</phone>
        <address>
          <street>653 11th Street</street>
          <city>Nampa</city>
          <state>Idaho</state>
        </address>
        <rank date-earned="2010-06-25">Tenderfoot</rank>
        <rank date-earned="2011-03-20">2nd Class</rank>
        <rank date-earned="2011-09-30">1st Class</rank>
        <meritbadge date-earned="2011-09-15">First Aid</meritbadge>
        <meritbadge date-earned="2011-09-10">Swimming</meritbadge>
        <meritbadge date-earned="2011-09-17">Archery</meritbadge>
      </scout>
      <scout>
        <firstName>Slightly</firstName>
        <lastName>Soiled</lastName>
        <phone>208-123-7654</phone>
        <address>
          <street>312 13th Street</street>
          <city>Nampa</city>
          <state>Idaho</state>
        </address>
        <rank date-earned="2011-10-20">Tenderfoot</rank>
      </scout>
      <scout>
        <firstName>Peter</firstName>
        <lastName>Panning</lastName>
        <phone>208-123-5678</phone>
        <address>
          <street>3 Star Road</street>
          <city>Nampa</city>
          <state>Idaho</state>
        </address>
        <rank date-earned="2009-05-03">Tenderfoot</rank>
        <rank date-earned="2009-09-23">2nd Class</rank>
        <rank date-earned="2010-01-11">1st Class</rank>
        <rank date-earned="2010-07-29">Star</rank>
        <rank date-earned="2011-02-13">Life</rank>
        <rank date-earned="2011-10-20">Eagle</rank>
        <meritbadge date-earned="2011-08-29">Astronomy</meritbadge>
        <meritbadge date-earned="2011-08-29">Aviation</meritbadge>
        <meritbadge date-earned="2011-09-18">Bird Study</meritbadge>
        <meritbadge date-earned="2011-09-06">Camping</meritbadge>
        <meritbadge date-earned="2011-09-09">Indian Lore</meritbadge>
        <meritbadge date-earned="2011-09-09">Music</meritbadge>
        <meritbadge date-earned="2011-09-18">Orienteering</meritbadge>
        <meritbadge date-earned="2011-09-06">Small-Boat Sailing</meritbadge>
        <meritbadge date-earned="2011-09-07">Sports</meritbadge>
        <meritbadge date-earned="2011-09-07">Swimming</meritbadge>
        <meritbadge date-earned="2011-09-07">Water Sports</meritbadge>
        <meritbadge date-earned="2011-09-08">Wilderness Survival</meritbadge>
        <meritbadge date-earned="2011-10-13">Wood Carving</meritbadge>
      </scout>
      <scout>
        <firstName>Jimmy</firstName>
        <lastName>Hooke</lastName>
        <phone>208-123-8765</phone>
        <address>
          <street>7 Cove Street</street>
          <city>Nampa</city>
          <state>Idaho</state>
        </address>
        <meritbadge date-earned="2011-09-29">Astronomy</meritbadge>
        <meritbadge date-earned="2011-09-29">Disabilities Awareness</meritbadge>
        <meritbadge date-earned="2011-08-18">Chemistry</meritbadge>
        <meritbadge date-earned="2011-09-06">Collections</meritbadge>
        <meritbadge date-earned="2011-09-09">Indian Lore</meritbadge>
        <meritbadge date-earned="2011-08-09">Law</meritbadge>
        <meritbadge date-earned="2011-09-13">Metalwork</meritbadge>
        <meritbadge date-earned="2011-09-13">Model Design and Building</meritbadge>
        <meritbadge date-earned="2011-10-07">Rowing</meritbadge>
        <meritbadge date-earned="2011-10-06">Small-Boat Sailing</meritbadge>
        <meritbadge date-earned="2011-10-07">Shotgun Shooting</meritbadge>
      </scout>
      <scout>
        <firstName>Alan</firstName>
        <lastName>Gatur</lastName>
        <phone>208-123-6789</phone>
        <address>
          <street>15 River Road</street>
          <city>Nampa</city>
          <state>Idaho</state>
        </address>
        <meritbadge date-earned="2011-09-27">Communications</meritbadge>
        <meritbadge date-earned="2011-09-29">Crime Prevention</meritbadge>
        <meritbadge date-earned="2011-08-13">Dentistry</meritbadge>
        <meritbadge date-earned="2011-10-03">Fishing</meritbadge>
        <meritbadge date-earned="2011-09-09">Mammal Study</meritbadge>
        <meritbadge date-earned="2011-08-09">Music</meritbadge>
        <meritbadge date-earned="2011-09-13">Nature</meritbadge>
        <meritbadge date-earned="2011-09-13">Pets</meritbadge>
        <meritbadge date-earned="2011-10-07">Reptile and Amphibian Study</meritbadge>
        <meritbadge date-earned="2011-10-06">Swimming</meritbadge>
        <meritbadge date-earned="2011-10-07">Water Sports</meritbadge>
      </scout>
    </troop>
    <troop number="145" name="Caldwell East">
      <scout>
        <firstName>Buzz</firstName>
        <lastName>Lightly</lastName>
        <phone>208-234-1928</phone>
        <address>
          <street>834 Infinity Lane</street>
          <city>Caldwell</city>
          <state>Idaho</state>
        </address>
        <rank date-earned="2010-06-28">Tenderfoot</rank>
        <rank date-earned="2010-09-21">2nd Class</rank>
        <rank date-earned="2011-03-30">1st Class</rank>
        <rank date-earned="2011-10-13">Star</rank>
        <meritbadge date-earned="2011-09-15">Astronomy</meritbadge>
        <meritbadge date-earned="2011-09-10">Aviation</meritbadge>
        <meritbadge date-earned="2011-09-17">Crime Prevention</meritbadge>
        <meritbadge date-earned="2011-09-17">Space Exploration</meritbadge>
      </scout>
      <scout>
        <firstName>Woody</firstName>
        <lastName>Ranger</lastName>
        <phone>208-234-8291</phone>
        <address>
          <street>14 Dusty Way</street>
          <city>Caldwell</city>
          <state>Idaho</state>
        </address>
        <rank date-earned="2011-10-20">Tenderfoot</rank>
        <meritbadge date-earned="2011-08-19">Horsemanship</meritbadge>
        <meritbadge date-earned="2011-09-11">Law</meritbadge>
      </scout>
      <scout>
        <firstName>Doug</firstName>
        <lastName>Slink</lastName>
        <phone>208-234-2837</phone>
        <address>
          <street>20 Spring Street</street>
          <city>Caldwell</city>
          <state>Idaho</state>
        </address>
        <rank date-earned="2011-04-17">Tenderfoot</rank>
        <rank date-earned="2011-10-13">2nd Class</rank>
        <meritbadge date-earned="2011-03-19">Dog Care</meritbadge>
        <meritbadge date-earned="2011-10-27">Pets</meritbadge>
      </scout>
      <scout>
        <firstName>Henry</firstName>
        <lastName>Hamm</lastName>
        <phone>208-234-7382</phone>
        <address>
          <street>312 Bank Ave</street>
          <city>Caldwell</city>
          <state>Idaho</state>
        </address>
        <meritbadge date-earned="2011-08-19">American Business</meritbadge>
        <meritbadge date-earned="2011-10-21">Chess</meritbadge>
        <meritbadge date-earned="2011-08-28">Coin Collecting</meritbadge>
        <meritbadge date-earned="2011-09-10">Entrepreneurship</meritbadge>
        <meritbadge date-earned="2011-09-19">Personal Management</meritbadge>
      </scout>
      <scout>
        <firstName>Tim</firstName>
        <lastName>Rexton</lastName>
        <phone>208-234-3645</phone>
        <address>
          <street>32 Spine Road</street>
          <city>Caldwell</city>
          <state>Idaho</state>
        </address>
        <meritbadge date-earned="2011-06-10">Archaeology</meritbadge>
        <meritbadge date-earned="2011-07-16">Computers</meritbadge>
        <meritbadge date-earned="2011-10-04">Reptile and Amphibian Study</meritbadge>
      </scout>
    </troop>
    <troop number="337" name="Weiser South">
      <scout>
        <firstName>Phineas</firstName>
        <lastName>Flynn</lastName>
        <phone>208-321-7654</phone>
        <address>
          <street>543 Summer Street</street>
          <city>Weiser</city>
          <state>Idaho</state>
        </address>
        <rank date-earned="2011-06-01">Tenderfoot</rank>
        <meritbadge date-earned="2011-06-02">Architecture</meritbadge>
        <meritbadge date-earned="2011-06-04">Chemistry</meritbadge>
        <meritbadge date-earned="2011-06-06">Nuclear Science</meritbadge>
        <meritbadge date-earned="2011-06-08">Inventing</meritbadge>
      </scout>
      <scout>
        <firstName>Ferb</firstName>
        <lastName>Fletcher</lastName>
        <phone>208-321-7654</phone>
        <address>
          <street>543 Summer Street</street>
          <city>Weiser</city>
          <state>Idaho</state>
        </address>
        <rank date-earned="2011-06-01">Tenderfoot</rank>
        <meritbadge date-earned="2011-06-03">Engineering</meritbadge>
        <meritbadge date-earned="2011-06-05">Electronics</meritbadge>
        <meritbadge date-earned="2011-06-07">Metalwork</meritbadge>
        <meritbadge date-earned="2011-06-09">Space Exploration</meritbadge>
      </scout>
      <scout>
        <firstName>Perry</firstName>
        <lastName>Plately</lastName>
        <phone>208-321-4567</phone>
        <address>
          <street>545 Summer Street</street>
          <city>Weiser</city>
          <state>Idaho</state>
        </address>
        <rank date-earned="2011-05-19">Tenderfoot</rank>
        <meritbadge date-earned="2011-05-29">Crime Prevention</meritbadge>
        <meritbadge date-earned="2011-06-08">Emergency Preparedness</meritbadge>
        <meritbadge date-earned="2011-06-02">Law</meritbadge>
