=== afane20/testPlan/src/main/webapp/cs213/public_html/xml/assign07.xsd
<?xml version = "1.0"?>
<!--An XML schema for the assign07_xsd.xml-->
<xsd:schema
   xmlns:xsd = "http://www.w3.org/2001/XMLSchema"
   targetNamespace = "http://ercanbracks.byui.edu/bsaSchema"
   xmlns = "http://ercanbracks.byui.edu/bsaSchema"
   elementFormDefault = "qualified">

   <xsd:element name = "firstname" type = "xsd:string" />
   <xsd:element name = "lastname" type = "xsd:string" />
   <xsd:element name = "phone" type = "xsd:string" />
   <xsd:element name = "street" type = "xsd:string" />
   <xsd:element name = "city" type = "xsd:string" />
   <xsd:element name = "state" type = "xsd:string" />
 
   <xsd:attribute name = "name" type = "xsd:string" />
   <xsd:attribute name = "troopnumber" type = "xsd:integer" />
   <xsd:attribute name = "unitname" type = "xsd:string" />
   <xsd:attribute name = "date-earned" type = "xsd:date" />


   <xsd:element name = "address">
      <xsd:complexType>
         <xsd:sequence>
            <xsd:element ref = "street" />
            <xsd:element ref = "city" />
            <xsd:element ref = "state" />
         </xsd:sequence>
      </xsd:complexType>
   </xsd:element>
   
   <xsd:element name = "rank">
      <xsd:complexType>
         <xsd:simpleContent>
            <xsd:extension base = "xsd:string">  
			   <xsd:attribute ref = "date-earned" use = "required"/>
			</xsd:extension>
		 </xsd:simpleContent>
      </xsd:complexType>
   </xsd:element>
   
   <xsd:element name = "meritbadge">
      <xsd:complexType>
         <xsd:simpleContent>
           <xsd:extension base = "xsd:string">  
               <xsd:attribute ref = "date-earned" use = "required"/>
		   </xsd:extension>
         </xsd:simpleContent>
      </xsd:complexType>
   </xsd:element>
   

   <xsd:element name = "bsa">
      <xsd:complexType>
         <xsd:sequence>
            <xsd:element ref = "council" minOccurs = "1" maxOccurs = "unbounded" />
         </xsd:sequence>
      </xsd:complexType>
   </xsd:element>
   
   <xsd:element name = "council">
      <xsd:complexType>
         <xsd:sequence>
            <xsd:element ref = "troop" minOccurs = "1" maxOccurs = "unbounded" />
         </xsd:sequence>
         <xsd:attribute ref = "name" use = "required"/>
      </xsd:complexType>
   </xsd:element>
   
   <xsd:element name = "troop">
      <xsd:complexType>
         <xsd:sequence>
            <xsd:element ref = "scout" minOccurs = "1" maxOccurs = "unbounded" />
         </xsd:sequence>
         <xsd:attribute ref = "troopnumber" use = "required" />
         <xsd:attribute ref = "unitname" use = "required"/>
      </xsd:complexType>
   </xsd:element>
   
   <xsd:element name = "scout">
      <xsd:complexType>
         <xsd:all>
            <xsd:element ref = "firstname" />
            <xsd:element ref = "lastname" />
            <xsd:element ref = "phone" />
            <xsd:element ref = "address" />
            <xsd:element ref = "rank" minOccurs = "0"/>
            <xsd:element ref = "meritbadge" minOccurs = "0"/>
         </xsd:all>
      </xsd:complexType>
   </xsd:element>
</xsd:schema>

=== afane20/testPlan/src/main/webapp/cs213/public_html/xml/assign07_xsd.xml
<?xml version = "1.0"?>
<!--
   Assignment 07
   Brother Ercanbrack, CS 373
-->
<!-- assign07_dtd.xml -->
<bsa xmlns = "http://ercanbracks.byui.edu/bsaSchema"
     xmlns:xsi = "http://www.w3.org/2001/XMLSchema-instance"
     xsi:schemaLocation = "http://157.201.194.254/~ercanbracks/assign07.xsd">

  <council name="Teton Peaks">
    <troop number="354" unit_name="Sugar 3rd Ward">
      <scout>
        <first>Lance</first>
	<last>Ercanbrack</last>
	<phone>2083132665</phone>
	<address>
	  <street>480 S. 1st West</street>
	  <city>Rexburg</city>
	  <state>Idaho</state>
	</address>
	<rank date-earned="2001-02-07">Tenderfoot</rank>
	<rank date-earned="2001-06-12">2nd Class</rank>
	<rank date-earned="2001-08-25">1st Class</rank>
	<rank date-earned="2002-02-15">Star</rank>
	<rank date-earned="2002-10-05">Life</rank>
	<rank date-earned="2004-06-28">Eagle</rank>
	<meritbadge date-earned="2001-02-01">Swimming</meritbadge>
	<meritbadge date-earned="2001-03-06">Camping</meritbadge>
	<meritbadge date-earned="2001-12-22">Life Saving</meritbadge>
	<meritbadge date-earned="2001-01-15">First Aid</meritbadge>
	<meritbadge date-earned="2001-06-17">Safety</meritbadge>
	<meritbadge date-earned="2002-06-19">Rifle Shooting</meritbadge>
	<meritbadge date-earned="2002-06-10">Cooking</meritbadge>
	<meritbadge date-earned="2002-06-14">Hiking</meritbadge>
	<meritbadge date-earned="2002-08-18">Orienteering</meritbadge>
	<meritbadge date-earned="2002-08-27">Personal Fitness</meritbadge>
	<meritbadge date-earned="2002-10-12">Cycling</meritbadge>
	<meritbadge date-earned="2003-02-05">Emergency Prepardness</meritbadge>
	<meritbadge date-earned="2003-04-05">Archery</meritbadge>
	<meritbadge date-earned="2003-04-18">Chemistry</meritbadge>
	<meritbadge date-earned="2003-04-12">Shotgun Shooting</meritbadge>
	<meritbadge date-earned="2003-08-11">Family Life</meritbadge>
	<meritbadge date-earned="2003-08-17">Pioneering</meritbadge>
	<meritbadge date-earned="2004-03-22">Citizenship in the Nation</meritbadge>
	<meritbadge date-earned="2004-03-26">Citizenship in the Community</meritbadge>
	<meritbadge date-earned="2004-05-01">Citizenship in the World</meritbadge>
	<meritbadge date-earned="2004-05-03">Environmental Science</meritbadge>

      </scout>
      <scout>
        <first>Dilbert</first>
	<last>Adams</last>
	<phone>1234567891</phone>
	<address>
	  <street>unknown</street>
	  <city>somewhere</city>
	  <state>Wisconsin</state>
	</address>
	<rank date-earned="2005-02-17">Tenderfoot</rank>
	<rank date-earned="2005-02-17">2nd Class</rank>
	<rank date-earned="2005-02-17">1st Class</rank>
	<meritbadge date-earned="2005-02-17">Orienteering</meritbadge>
      </scout>
      <scout>
        <first>Mini</first>
	<last>Me</last>
	<phone>5558675309</phone>
	<address>
	  <street>1994 17th Street</street>
	  <city>Metropolis</city>
	  <state>Iowa</state>
	</address>
	<rank date-earned="2001-02-17">Tenderfoot</rank>
	<rank date-earned="2001-02-17">2nd Class</rank>
	<rank date-earned="2001-06-17">1st Class</rank>
	<rank date-earned="2002-06-17">Star</rank>
	<meritbadge date-earned="2001-01-15">First Aid</meritbadge>
	<meritbadge date-earned="2001-06-17">Safety</meritbadge>
	<meritbadge date-earned="2002-06-19">Rifle Shooting</meritbadge>
	<meritbadge date-earned="2002-06-10">Cooking</meritbadge>
	<meritbadge date-earned="2002-06-14">Hiking</meritbadge>
	<meritbadge date-earned="2002-08-18">Orienteering</meritbadge>
      </scout>
      <scout>
        <first>Bob</first>
	<last>Dillon</last>
	<phone>5556667777</phone>
	<address>
	  <street>this street</street>
	  <city>Hell</city>
	  <state>Michigan</state>
	</address>
	<rank date-earned="2005-02-17">Tenderfoot</rank>
      </scout>
      <scout>
        <first>Daper</first>
	<last>Dan</last>
	<phone>7894561234</phone>
	<address>
	  <street>1832 W. 1st</street>
	  <city>Boise</city>
	  <state>Idaho</state>
	</address>
	<rank date-earned="2005-02-17">Tenderfoot</rank>
	<rank date-earned="2005-08-17">2nd Class</rank>
	<meritbadge date-earned="2005-05-17">Tracking</meritbadge>
	<meritbadge date-earned="2005-07-17">Orienteering</meritbadge>
	<meritbadge date-earned="2005-08-17">Snacking</meritbadge>
      </scout>
      <scout>
        <first>Charlie</first>
	<last>Brown</last>
	<phone>4567891235</phone>
	<address>
	  <street>123 D street</street>
	  <city>Beagle Town</city>
	  <state>California</state>
	</address>
	<rank date-earned="2004-08-17">Tenderfoot</rank>
	<rank date-earned="2005-02-17">2nd Class</rank>
	<rank date-earned="2005-07-17">1st Class</rank>
	<meritbadge date-earned="2005-02-17">Orienteering</meritbadge>
     </scout>
    </troop>
    <troop number="55" unit_name="Beavers">
      <scout>
        <first>Dan</first>
	<last>Marino</last>
	<phone>7894561231</phone>
	<address>
	  <street>125 F. Street</street>
	  <city>Pica</city>
	  <state>New Mexico</state>
	</address>
	<rank date-earned="2005-02-17">Tenderfoot</rank>
	<rank date-earned="2005-02-17">2nd Class</rank>
	<rank date-earned="2005-02-17">1st Class</rank>
	<meritbadge date-earned="2005-02-17">Rifle Shooting</meritbadge>
	<meritbadge date-earned="2005-02-17">Orienteering</meritbadge>
     </scout>
      <scout>
        <first>Marty</first>
	<last>McFly</last>
	<phone>7894561235</phone>
	<address>
	  <street>145 Future Street</street>
	  <city>Winsor</city>
	  <state>Massachusetts</state>
	</address>
	<rank date-earned="2004-02-17">Tenderfoot</rank>
	<rank date-earned="2004-09-17">2nd Class</rank>
	<rank date-earned="2005-02-17">1st Class</rank>
	<rank date-earned="2005-10-17">Star</rank>
	<meritbadge date-earned="2005-02-17">Swimming</meritbadge>
	<meritbadge date-earned="2005-02-17">Camping</meritbadge>
	<meritbadge date-earned="2005-02-17">Life Saving</meritbadge>
	<meritbadge date-earned="2005-02-17">First Aid</meritbadge>
	<meritbadge date-earned="2005-02-17">Safety</meritbadge>
	<meritbadge date-earned="2005-02-17">Rifle Shooting</meritbadge>
      </scout>
      <scout>
        <first>Matthew</first>
	<last>Elliott</last>
	<phone>4563698521</phone>
	<address>
	  <street>6879 Lost Street</street>
	  <city>Salt Lake City</city>
	  <state>Utah</state>
	</address>
	<rank date-earned="2001-02-17">Tenderfoot</rank>
	<rank date-earned="2001-08-17">2nd Class</rank>
	<rank date-earned="2002-04-17">1st Class</rank>
	<rank date-earned="2003-02-17">Star</rank>
	<rank date-earned="2004-02-17">Life</rank>
	<meritbadge date-earned="2001-02-01">Swimming</meritbadge>
	<meritbadge date-earned="2001-03-06">Camping</meritbadge>
	<meritbadge date-earned="2001-12-22">Life Saving</meritbadge>
	<meritbadge date-earned="2001-01-15">First Aid</meritbadge>
	<meritbadge date-earned="2002-06-17">Safety</meritbadge>
	<meritbadge date-earned="2002-06-19">Rifle Shooting</meritbadge>
	<meritbadge date-earned="2002-06-10">Cooking</meritbadge>
	<meritbadge date-earned="2002-06-14">Hiking</meritbadge>
	<meritbadge date-earned="2002-08-18">Orienteering</meritbadge>
	<meritbadge date-earned="2002-08-27">Personal Fitness</meritbadge>
	<meritbadge date-earned="2002-10-12">Cycling</meritbadge>
	<meritbadge date-earned="2003-02-05">Emergency Prepardness</meritbadge>
	<meritbadge date-earned="2003-04-05">Archery</meritbadge>
      </scout>
      <scout>
        <first>Keith</first>
	<last>Urban</last>
	<phone>4561235465</phone>
	<address>
	  <street>1459 Downunder Street</street>
	  <city>Melborne</city>
	  <state>Austrailia</state>
	</address>
      </scout>
      <scout>
        <first>Mike</first>
	<last>Connors</last>
	<phone>1235467896</phone>
	<address>
	  <street>480 S. 1st West</street>
	  <city>Rexburg</city>
	  <state>Idaho</state>
	</address>
      </scout>
      <scout>
        <first>Biff</first>
	<last>Jones</last>
	<phone>4561232585</phone>
	<address>
	  <street>500 S. 550 W.</street>
	  <city>Burley</city>
	  <state>Idaho</state>
	</address>
      </scout>
    </troop>
  </council>
</bsa>
